# Generated by Django 4.2.6 on 2023-10-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Negative_Reviews",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, null=True)),
                ("fullname", models.CharField(max_length=100, null=True)),
                ("product", models.CharField(max_length=100, null=True)),
                ("review", models.CharField(max_length=10000, null=True)),
                ("rating", models.IntegerField(null=True)),
                ("label", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "negative_reviews",
                "managed": False,
            },
        ),
    ]
